In [21]:
"""
1. Load the Dataset
   Load the dataset into a pandas DataFrame.
   Inspect the dataset (e.g. head() , info() , describe() )
"""

'Load the Dataset\n   Load the dataset into a pandas DataFrame.\n   Inspect the dataset (e.g. head() , info() , describe() )\n'

In [20]:
import pandas as pd

In [4]:
DF = pd.read_csv('daily-minimum-temperatures-in-me.csv')

In [6]:
DF.head()

       Date Daily minimum temperatures
0  1/1/1981                       20.7
1  1/2/1981                       17.9
2  1/3/1981                       18.8
3  1/4/1981                       14.6
4  1/5/1981                       15.8

In [8]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        3650 non-null   object
 1   Daily minimum temperatures  3650 non-null   object
dtypes: object(2)
memory usage: 57.2+ KB

In [10]:
DF.describe()

              Date Daily minimum temperatures
count         3650                       3650
unique        3650                        230
top     12/31/1990                         10
freq             1                         51

In [ ]:
"""
2.Convert Date Column
  Convert the date column to a datetime object
  Verify the data type of the column
"""

In [14]:
import datetime as dt
from datetime import datetime,date,time,timedelta

In [29]:
DF['Date'] = pd.to_datetime(DF['Date'])
type(DF['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
"""
3.Extract Features
  -Extract the year, month, and day from the date column and
   add them as new columns.

  -Create a column for the day of the week (e.g., Monday, Tuesday).
"""

In [34]:
DF['year'] = DF['Date'].dt.year
DF['month'] = DF['Date'].dt.month
DF['day'] = DF['Date'].dt.day
DF[['year','month','day']].head()

   year  month  day
0  1981      1    1
1  1981      1    2
2  1981      1    3
3  1981      1    4
4  1981      1    5

In [37]:
DF['dayOfWeek'] = DF['Date'].dt.day_name()
DF['dayOfWeek'].head()

0    Thursday
1      Friday
2    Saturday
3      Sunday
4      Monday
Name: dayOfWeek, dtype: object

In [22]:
"""
4.Filter Data
  - Filter the dataset to include only the temperatures
    from a specific year (e.g., 1985)

  - Count how many days in 1985 had a temperature below
   a certain threshold (e.g., 10°C)
"""

'\n4.Filter Data\n  - Filter the dataset to include only the temperatures \n    from a specific year (e.g., 1985)\n\n  - Count how many days in 1985 had a temperature below\n   a certain threshold (e.g., 10°C)\n'

In [48]:
DF[DF['year'] == 1985]

           Date Daily minimum temperatures  year  month  day  dayOfWeek
1460 1985-01-01                       13.3  1985      1    1    Tuesday
1461 1985-01-02                       15.2  1985      1    2  Wednesday
1462 1985-01-03                       13.1  1985      1    3   Thursday
1463 1985-01-04                       12.7  1985      1    4     Friday
1464 1985-01-05                       14.6  1985      1    5   Saturday
...         ...                        ...   ...    ...  ...        ...
1820 1985-12-27                       11.5  1985     12   27     Friday
1821 1985-12-28                       10.8  1985     12   28   Saturday
1822 1985-12-29                         12  1985     12   29     Sunday
1823 1985-12-30                       16.3  1985     12   30     Monday
1824 1985-12-31                       14.4  1985     12   31    Tuesday

[365 rows x 6 columns]

In [63]:
DF['Temperature'] = pd.to_numeric(DF['Daily minimum temperatures'], errors='coerce')

In [87]:
DF[(DF['year'] == 1985) & (DF['Temperature'] < 10)]['day'].count()

np.int64(142)

In [ ]:
"""
5.Analyze Time Periods
 - Group the data by year and calculate the average minimum
   temperature for each year.

 - Find the year with the highest and lowest average minimum temperatures.
"""

In [89]:
DF.groupby('year')['Temperature'].min()

year
1981    2.1
1982    0.0
1983    0.0
1984    0.7
1985    0.3
1986    0.8
1987    1.5
1988    2.8
1989    0.5
1990    2.1
Name: Temperature, dtype: float64

In [105]:
DF.groupby('year')['Temperature'].mean().idxmax()

np.int32(1988)

In [106]:
DF.groupby('year')['Temperature'].mean().idxmin()

np.int32(1984)

In [107]:
#  6.Summary: Write a brief summary (1-2 paragraphs) of your findings.

In [108]:
"""
-Days with Temperature Below 10°C in 1985:

In 1985, there were 142 days where the daily minimum temperature
was below 10°C. This indicates that the year experienced many
cold days.
"""

SyntaxError: incomplete input (<ipython-input-108-0f439babf70a>, line 1)

In [109]:
"""
-Year with the Highest Average Minimum Temperature:

The year with the highest average minimum temperature is 1988.
This suggests that 1988 was relatively warmer compared
to other years in the dataset.

"""

'\n-Year with the Highest Average Minimum Temperature:\nThe year with the highest average minimum temperature is 1988.\nThis suggests that 1988 was relatively warmer compared \nto other years in the dataset.\n\n'

In [ ]:
"""
-Year with the Lowest Average Minimum Temperature:

The year with the lowest average minimum temperature is 1984.
This indicates that 1984 was one of the coldest years
in terms of minimum temperatures.
"""